"""Render every 2O/2I Gram parameter into the PDF; no external data or decimals."""
import argparse
from pathlib import Path

from su2_exact_ade import classify_group


def render_catalogue():
    lines=[r'% Generated by python -m scripts.render_exact_catalogue; exact integer enumeration.',
           r'\section{2O、2I 全部非退化类型的可代入参数表}',
           r'\label{sec:complete-gram-table}',
           '本节在 PDF 内完整列出所有参数，不要求专家另行运行代码才能看到表。',
           r'每个六位键 $K=d_1d_2d_3d_4d_5d_6$ 后的下标是锚定重数 $m$。',
           r'从各群的字母表取 $x_j=A_{d_j}$（字母索引从 0 开始），构造',
           r'\[',
           r'G(K)=\begin{pmatrix}1&x_1&x_2&x_3\\x_1&1&x_4&x_5\\',
           r'x_2&x_4&1&x_6\\x_3&x_5&x_6&1\end{pmatrix},\qquad',
           r'(c_1,\ldots,c_6)=(x_1,x_2,x_3,x_6,x_5,x_4).',
           r'\]',
           r'这些 $c_j$ 与 $\det G(K)$ 直接代入第 \ref{sec:symbolic-ade} 节的完整相位式。',
           r'有序群输入另给 $\operatorname{sgn}D$；只看无向类型不能恢复取向。',
           r'字母表按整数对编码排序，并非按实数大小排序。每行从左到右读，',
           r'逐行顺序与 JSON 的零起始类型索引一致。重数不是体积。']
    alphabets={
        '2O':r'(-1,-\tfrac12,-\tfrac{\sqrt2}{2},0,\tfrac{\sqrt2}{2},\tfrac12,1)',
        '2I':r'(-1,-\tfrac12,-\tfrac{1+\sqrt5}{4},\tfrac{-1+\sqrt5}{4},0,'
             r'\tfrac{1-\sqrt5}{4},\tfrac{1+\sqrt5}{4},\tfrac12,1)'}
    for name in ('2O','2I'):
        rows=classify_group(name)['types']
        lines.extend([r'\subsection{'+name+'：'+str(len(rows))+' 类}',
                      r'\[ A='+alphabets[name]+r'.\]',
                      r'{\small\begin{longtable}{@{}llllll@{}}',r'\toprule',
                      ' & '.join([r'$K_m$']*6)+r'\\\midrule\endhead'])
        entries=[r'\texttt{'+''.join(map(str,row['gram_key']))+r'}$_{'
                 +str(row['anchored_multiplicity'])+'}$' for row in rows]
        for offset in range(0,len(entries),6):
            batch=entries[offset:offset+6]
            lines.append(' & '.join(batch+['']*(6-len(batch)))+r'\\')
        lines.extend([r'\bottomrule',r'\end{longtable}}'])
    return '\n'.join(lines)+'\n'


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--output',type=Path,default=Path('paper/su2_exact_catalogue.tex'))
    args=parser.parse_args()
    args.output.parent.mkdir(parents=True,exist_ok=True)
    args.output.write_text(render_catalogue())
    print('Wrote',args.output)


if __name__=='__main__':
    main()
