"""Render every 2O/2I type with its exact Li2-free volume into the PDF.

Pure exact enumeration: Gram keys (integer pairs), chamber counts, rational parts
and certified basis coefficients.  No external data files and no decimals.
Also renders the certified dihedral-angle tables (paper/su2_polar_certificates.tex).
"""
import argparse
from fractions import Fraction
from pathlib import Path

from su2_exact_ade import classify_group
from su2_polar_dual import FIELD, Surd, angle_system, polar_catalogue

ALPHABETS = {
    '2O': r'(-1,-\tfrac12,-\tfrac{\sqrt2}{2},0,\tfrac{\sqrt2}{2},\tfrac12,1)',
    '2I': r'(-1,-\tfrac12,-\tfrac{1+\sqrt5}{4},\tfrac{-1+\sqrt5}{4},0,'
          r'\tfrac{1-\sqrt5}{4},\tfrac{1+\sqrt5}{4},\tfrac12,1)'}
BASIS_TEX = {'2O': (r'\beta',), '2I': ('A', 'B', 'C')}


def tex_fraction(x):
    x = Fraction(x)
    if x.denominator == 1:
        return str(x.numerator)
    sign = '-' if x < 0 else ''
    return sign+r'\tfrac{'+str(abs(x.numerator))+'}{'+str(x.denominator)+'}'


def tex_surd(key, d):
    a, b = Fraction(key[0]), Fraction(key[1])
    if not b:
        return tex_fraction(a)
    rad = r'\sqrt'+str(d)
    bt = ('' if abs(b) == 1 else tex_fraction(abs(b)))+rad
    if not a:
        return ('-' if b < 0 else '')+bt
    return tex_fraction(a)+('-' if b < 0 else '+')+bt


def tex_angle(r, coeff, basis_keys, name):
    parts = []
    if r:
        parts.append(tex_fraction(r)+r'\pi')
    for key, sym in zip(basis_keys, BASIS_TEX[name]):
        c = coeff.get(key, Fraction(0))
        if not c:
            continue
        term = ('' if abs(c) == 1 else tex_fraction(abs(c)))+sym
        parts.append(('-' if c < 0 else ('+' if parts else ''))+term)
    return ''.join(parts) or '0'


def render_catalogue():
    lines = [r'% Generated by python -m scripts.render_exact_catalogue; exact integer enumeration.',
             r'\section{2O、2I 全部非退化类型：参数与精确体积短表}',
             r'\label{sec:complete-gram-table}',
             '本节在 PDF 内完整列出所有类型及其精确体积，不要求专家另行运行代码。',
             r'每个六位键 $K=d_1d_2d_3d_4d_5d_6$ 后的下标是锚定重数 $m$。',
             r'从各群的字母表取 $x_j=A_{d_j}$（字母索引从 0 开始），构造',
             r'\[',
             r'G(K)=\begin{pmatrix}1&x_1&x_2&x_3\\x_1&1&x_4&x_5\\',
             r'x_2&x_4&1&x_6\\x_3&x_5&x_6&1\end{pmatrix},\qquad',
             r'(c_1,\ldots,c_6)=(x_1,x_2,x_3,x_6,x_5,x_4).',
             r'\]',
             r'这些 $c_j$ 与 $\det G(K)$ 可代入第 \ref{sec:symbolic-ade} 节的完整相位式；',
             r'同一类型的实际体积由第 \ref{sec:polar-dual} 节的极对偶公式给出：',
             r'\[',
             r'V=a\pi^2+\frac{\pi}{2}\sum_jb_j\Theta_j,\qquad',
             r'\omega_k=\exp\!\Bigl[-ik\operatorname{sgn}(D)\Bigl(a\pi+\tfrac12\sum_jb_j\Theta_j\Bigr)\Bigr],',
             r'\]',
             r'其中两群的基底常数为',
             r'\[',
             r'2O:\ \Theta=\beta=\arctan\tfrac1{\sqrt2},\qquad',
             r'2I:\ \Theta=(A,B,C)=\bigl(\arctan\tfrac12,\arctan\tfrac1{\sqrt5},\arctan\sqrt{15}\bigr).',
             r'\]',
             r'$N$ 是极对偶中的 Coxeter 室数（$|W|=1152$ 或 $14400$），$a,b_j$ 为有理数；',
             r'$b=0$ 当且仅当体积是 $\pi^2$ 的有理倍数（定理 \ref{thm:angle-independence}）。',
             r'有序群输入另给 $\operatorname{sgn}D$；只看无向类型不能恢复取向。',
             r'字母表按整数对编码排序，并非按实数大小排序；行序与 JSON 的零起始类型索引一致。']
    for name in ('2O', '2I'):
        rows = classify_group(name)['types']
        volumes = polar_catalogue(name)['types']
        assert [r['gram_key'] for r in rows] == [v['gram_key'] for v in volumes]
        rational = sum(v['rational_volume'] for v in volumes)
        lines.extend([r'\subsection{'+name+'：'+str(len(rows))+' 类（其中 '+str(rational)+' 类为有理体积）}',
                      r'\[ A='+ALPHABETS[name]+r'.\]',
                      r'{\footnotesize\begin{longtable}{@{}lrll@{\hspace{2em}}lrll@{}}', r'\toprule',
                      ' & '.join([r'$K_m$', '$N$', '$a$', '$b$']*2)+r'\\\midrule\endhead'])
        entries = []
        for row, vol in zip(rows, volumes):
            b = vol['basis_coefficients']
            btex = '0' if not any(b) else ('$'+tex_fraction(b[0])+'$' if len(b) == 1 else
                                            '$('+','.join(tex_fraction(x) for x in b)+')$')
            entries.append([r'\texttt{'+''.join(map(str, row['gram_key']))+r'}$_{'
                            + str(row['anchored_multiplicity'])+'}$', str(vol['chambers']),
                            '$'+tex_fraction(vol['rational_part'])+'$', btex])
        for offset in range(0, len(entries), 2):
            batch = entries[offset:offset+2]
            cells = [c for e in batch for c in e]+['']*(4*(2-len(batch)))
            lines.append(' & '.join(cells)+r'\\')
        lines.extend([r'\bottomrule', r'\end{longtable}}'])
    return '\n'.join(lines)+'\n'


def render_certificates():
    lines = [r'% Generated by python -m scripts.render_exact_catalogue; exact Q(sqrt d) identities.']
    names = {'complement': '互余', 'double': '倍角', 'sum': '和角', 'difference': '差角'}
    for name in ('2O', '2I'):
        d = FIELD[name]
        system = angle_system(name)
        basis = system['basis']
        lines.extend([r'\paragraph{'+name+r' 的无理二面角表。}',
                      r'下表的 $\theta[T]\in(0,\pi/2)$ 满足 $\tan^2\theta[T]=T$；',
                      r'$\cos\theta<0$ 的二面角取 $\pi-\theta[T]$。',
                      r'{\small\begin{longtable}{@{}ll@{\hspace{3em}}ll@{}}\toprule',
                      r'$T=\tan^2\theta$ & $\theta$ & $T=\tan^2\theta$ & $\theta$\\\midrule\endhead'])
        items = sorted(system['angles'].items(), key=lambda kv: (kv[0][1] != 0, kv[0]))
        cells = ['$'+tex_surd(k, d)+'$ & $'+tex_angle(r, c, basis, name)+'$' for k, (r, c) in items]
        for offset in range(0, len(cells), 2):
            batch = cells[offset:offset+2]+['&']*(2-len(cells[offset:offset+2]))
            lines.append(' & '.join(batch)+r'\\')
        lines.extend([r'\bottomrule\end{longtable}}',
                      r'\paragraph{'+name+' 的证书（'+str(len(system['certificate']))+' 条精确恒等式）。}',
                      r'{\small\begin{longtable}{@{}rll@{}}\toprule 类型 & 关系 & \\\midrule\endhead'])
        for desc, rel, r in system['certificate']:
            terms = []
            for k, c in rel.items():
                c = Fraction(c)
                coef = '' if abs(c) == 1 else str(abs(c.numerator))
                terms.append(('-' if c < 0 else ('+' if terms else ''))+coef+r'\theta['+tex_surd(k, d)+']')
            lines.append(names[desc]+' & $'+''.join(terms)+'='+(tex_fraction(r)+r'\pi' if r else '0')+r'$ & \\')
        lines.extend([r'\bottomrule\end{longtable}}'])
    return '\n'.join(lines)+'\n'


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--output', type=Path, default=Path('paper/su2_exact_catalogue.tex'))
    parser.add_argument('--certificates', type=Path, default=Path('paper/su2_polar_certificates.tex'))
    args = parser.parse_args()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render_catalogue())
    args.certificates.write_text(render_certificates())
    print('Wrote', args.output, 'and', args.certificates)


if __name__ == '__main__':
    main()
