"""Li2-free exact volumes of tetrahedra whose vertices lie in 2T, 2O or 2I.

For a nondegenerate spherical tetrahedron T with polar dual T*,

    vol T + vol T* = pi^2 + 1/2 sum_e l_e th_e - pi/2 sum_e l_e      (Schlaefli),

every edge length l_e is a rational multiple of pi (p_i^{-1} p_j has finite
order), and T* is cut out by mirrors v^perp, v in G, of the finite reflection
group W generated by x -> -v conj(x) v.  Hence vol T* = N * 2 pi^2/|W| with N an
exact chamber count.  Every dihedral angle th_e is reduced, by certified
double/complement/sum identities in Q(sqrt d), to rational multiples of pi plus a
Q-combination of a fixed basis: none (2T), arctan(1/sqrt 2) (2O), and
arctan(1/2), arctan(1/sqrt 5), arctan(sqrt 15) (2I).

The result is the SAME geometric volume as the Murakami Li2 formula (no change of
representative).  No floating point is used: all signs are decided exactly in
Q(sqrt d).  Proof: docs/review-0923/SU2_POLAR_DUAL_EXACT.md.
"""
from copy import deepcopy
from fractions import Fraction
from functools import lru_cache
from itertools import combinations
from math import isqrt

import sympy as s
from su2_exact_ade import classify_group, integer_pair_group
from su2_symbolic import EDGE_PAIRS, exact_level, unit_quaternion

FIELD = {'2T': 0, '2O': 2, '2I': 5}
# tan^2 of the basis angles (all rational); the basis angle is arctan(sqrt(T)).
BASIS_TAN2 = {'2T': (), '2O': (Fraction(1, 2),),
              '2I': (Fraction(1, 4), Fraction(1, 5), Fraction(15))}
RHO = (7, 3, 2, 1)   # generic point: checked below to lie on no mirror


class Surd:
    """Exact a + b sqrt(d), a and b rational, d in {0, 2, 5}."""
    __slots__ = ('a', 'b', 'd')

    def __init__(self, a, b=0, d=0):
        self.a, self.b, self.d = Fraction(a), Fraction(b), d
        if d == 0 and self.b:
            raise ValueError('sqrt(0) part must vanish')

    def _c(self, o):
        return o if isinstance(o, Surd) else Surd(o, 0, self.d)

    def __add__(self, o):
        o = self._c(o)
        return Surd(self.a+o.a, self.b+o.b, self.d)
    __radd__ = __add__

    def __sub__(self, o):
        o = self._c(o)
        return Surd(self.a-o.a, self.b-o.b, self.d)

    def __rsub__(self, o):
        return self._c(o)-self

    def __neg__(self):
        return Surd(-self.a, -self.b, self.d)

    def __mul__(self, o):
        o = self._c(o)
        return Surd(self.a*o.a+self.d*self.b*o.b, self.a*o.b+self.b*o.a, self.d)
    __rmul__ = __mul__

    def norm(self):
        return self.a*self.a-self.d*self.b*self.b

    def __truediv__(self, o):
        o = self._c(o)
        n = o.norm()
        if n == 0:
            raise ZeroDivisionError('Division by zero in Q(sqrt d)')
        return self*Surd(o.a/n, -o.b/n, self.d)

    def __rtruediv__(self, o):
        return self._c(o)/self

    def __eq__(self, o):
        o = self._c(o)
        return self.a == o.a and self.b == o.b

    def __hash__(self):
        return hash((self.a, self.b))

    def sign(self):
        return surd_sign(self.a, self.b, self.d)

    def __lt__(self, o):
        return (self-o).sign() < 0

    def __gt__(self, o):
        return (self-o).sign() > 0

    def key(self):
        return (self.a, self.b)

    def sympy(self):
        return s.Rational(self.a.numerator, self.a.denominator) \
            + s.Rational(self.b.numerator, self.b.denominator)*s.sqrt(self.d)

    def __repr__(self):
        return f'Surd({self.a}, {self.b}, {self.d})'


def surd_sign(a, b, d):
    """Exact sign of a + b sqrt(d)."""
    sa = (a > 0)-(a < 0)
    sb = (b > 0)-(b < 0)
    if sb == 0 or d == 0:
        return sa
    if sa == 0 or sa == sb:
        return sa or sb
    c = a*a-d*b*b
    return sa if c > 0 else sb if c < 0 else 0


def _rational_sqrt(f):
    f = Fraction(f)
    if f < 0:
        return None
    n, m = isqrt(f.numerator), isqrt(f.denominator)
    return Fraction(n, m) if n*n == f.numerator and m*m == f.denominator else None


def surd_sqrt(x):
    """Exact nonnegative square root in Q(sqrt d), or None if it does not exist."""
    if x.sign() < 0:
        return None
    if x.sign() == 0:
        return Surd(0, 0, x.d)
    if x.b == 0:
        r = _rational_sqrt(x.a)
        if r is not None:
            return Surd(r, 0, x.d)
        r = _rational_sqrt(x.a/x.d) if x.d else None
        return Surd(0, r, x.d) if r is not None else None
    n = _rational_sqrt(x.norm())
    if n is None:
        return None
    for sign in (1, -1):
        u = _rational_sqrt((x.a+sign*n)/2)
        if u:
            for c in (Surd(u, x.b/(2*u), x.d), Surd(-u, -x.b/(2*u), x.d)):
                if c*c == x and c.sign() > 0:
                    return c
    return None


def _check_group(name):
    if name not in FIELD:
        raise ValueError('Use 2T, 2O, or 2I')


@lru_cache(maxsize=3)
def group_vectors(name):
    """Unit quaternions of the group as exact Surd 4-tuples (same order as su2_exact_ade)."""
    _check_group(name)
    d = FIELD[name]
    return tuple(tuple(Surd(Fraction(a, 4), Fraction(b, 4), d) for a, b in q)
                 for q in integer_pair_group(name))


@lru_cache(maxsize=3)
def _index(name):
    return {tuple(x.key() for x in v): i for i, v in enumerate(group_vectors(name))}


def dot(u, v):
    total = u[0]*v[0]
    for x, y in zip(u[1:], v[1:]):
        total = total+x*y
    return total


def quaternion_product(left, right):
    """Negative-cross convention of su2_symbolic, on Surd coordinates."""
    a, x, y, z = left
    b, u, v, w = right
    return (a*b-x*u-y*v-z*w, a*u+b*x-y*w+z*v, a*v+b*y-z*u+x*w, a*w+b*z-x*v+y*u)


def _det3(m):
    return (m[0][0]*(m[1][1]*m[2][2]-m[1][2]*m[2][1])
            - m[0][1]*(m[1][0]*m[2][2]-m[1][2]*m[2][0])
            + m[0][2]*(m[1][0]*m[2][1]-m[1][1]*m[2][0]))


def cofactor(m, i, j):
    minor = [[m[r][c] for c in range(4) if c != j] for r in range(4) if r != i]
    value = _det3(minor)
    return value if (i+j) % 2 == 0 else -value


def determinant(vectors):
    """det of the 4x4 matrix whose columns are the given vectors."""
    rows = [[v[r] for v in vectors] for r in range(4)]
    return sum((rows[0][j]*cofactor(rows, 0, j) for j in range(4)), Surd(0, 0, vectors[0][0].d))


# ---------------------------------------------------------------------------
# Reflection group W = <s_v : v in G> and its chambers
# ---------------------------------------------------------------------------

@lru_cache(maxsize=3)
def weyl_chamber_masks(name):
    """Exact orbit W.rho, returned as bitmasks of the roots g with <w rho, g> > 0.

    s_v(x) = x - 2<x,v>v maps G to G (s_v(g) = -v conj(g) v), so G is a root
    system and W is finite; W acts simply transitively on chambers, and rho lies
    in an open chamber (asserted), so the orbit has one point per chamber.
    Coordinates are kept as integers: x = X/64 with X in Z[sqrt d]^4.
    """
    _check_group(name)
    d = FIELD[name]
    roots = integer_pair_group(name)          # (a,b) pairs meaning (a+b sqrt d)/4
    mirrors = []
    for v in roots:
        if tuple((-a, -b) for a, b in v) not in mirrors:
            mirrors.append(v)

    def reflect(X, V):
        p = sum(xa*va+d*xb*vb for (xa, xb), (va, vb) in zip(X, V))
        r = sum(xa*vb+xb*va for (xa, xb), (va, vb) in zip(X, V))
        out = []
        for (xa, xb), (va, vb) in zip(X, V):
            ta, tb = p*va+d*r*vb, p*vb+r*va          # (X.V) V ; must be divisible by 8
            if ta % 8 or tb % 8:
                raise ArithmeticError('Unexpected denominator in the Weyl orbit')
            out.append((xa-ta//8, xb-tb//8))
        return tuple(out)

    start = tuple((64*c, 0) for c in RHO)
    for V in mirrors:
        p = sum(xa*va for (xa, _), (va, _) in zip(start, V))
        r = sum(xa*vb for (xa, _), (_, vb) in zip(start, V))
        if surd_sign(p, r, d) == 0:
            raise ArithmeticError('rho lies on a mirror')
    seen = {start}
    frontier = [start]
    while frontier:
        nxt = []
        for X in frontier:
            for V in mirrors:
                Y = reflect(X, V)
                if Y not in seen:
                    seen.add(Y)
                    nxt.append(Y)
        frontier = nxt
    masks = []
    for X in seen:
        mask = 0
        for i, g in enumerate(roots):
            p = sum(xa*ga+d*xb*gb for (xa, xb), (ga, gb) in zip(X, g))
            r = sum(xa*gb+xb*ga for (xa, xb), (ga, gb) in zip(X, g))
            sg = surd_sign(p, r, d)
            if sg == 0:
                raise ArithmeticError('An orbit point lies on a mirror')
            if sg > 0:
                mask |= 1 << i
        masks.append(mask)
    return len(seen), tuple(masks)


def chamber_count(name, indices):
    """N = number of W-chambers inside the polar dual {x : <x, v_i> >= 0}."""
    order, masks = weyl_chamber_masks(name)
    need = 0
    for i in indices:
        need |= 1 << i
    return order, sum(1 for m in masks if m & need == need)


# ---------------------------------------------------------------------------
# Rational angles and the certified irrational-angle basis
# ---------------------------------------------------------------------------

def rational_cos2_table(d):
    """cos^2(pi r), 0<=r<=1/2, lying in Q(sqrt d).

    If theta = pi k/N (lowest terms) has cos^2 in Q(sqrt d), then cos(2 theta)
    has degree <= 2, so phi(N') <= 4 for the order N' of exp(2 i theta); hence
    N' in {1,2,3,4,5,6,8,10,12} and these entries are exhaustive.
    """
    table = {(Fraction(1), Fraction(0)): Fraction(0), (Fraction(3, 4), Fraction(0)): Fraction(1, 6),
             (Fraction(1, 2), Fraction(0)): Fraction(1, 4), (Fraction(1, 4), Fraction(0)): Fraction(1, 3),
             (Fraction(0), Fraction(0)): Fraction(1, 2)}
    if d == 2:
        table[(Fraction(1, 2), Fraction(1, 4))] = Fraction(1, 8)
        table[(Fraction(1, 2), Fraction(-1, 4))] = Fraction(3, 8)
    if d == 5:
        table[(Fraction(5, 8), Fraction(1, 8))] = Fraction(1, 10)
        table[(Fraction(3, 8), Fraction(1, 8))] = Fraction(1, 5)
        table[(Fraction(5, 8), Fraction(-1, 8))] = Fraction(3, 10)
        table[(Fraction(3, 8), Fraction(-1, 8))] = Fraction(2, 5)
    return table


def rational_angle(sign, cos2):
    """Return r with the angle = pi r if theta/pi is rational, else None."""
    r = rational_cos2_table(cos2.d).get(cos2.key())
    if r is None:
        return None
    return r if sign >= 0 else 1-r


def edge_fraction(cosine):
    """Exact q with cos(pi q) = cosine for the finitely many group inner products."""
    r = rational_angle(cosine.sign(), cosine*cosine)
    if r is None:
        raise ArithmeticError('Group inner product is not a rational angle')
    return r


def _tan2_rational_table(d):
    """tan^2(pi r) for rational r in (0, 1/2) with value in Q(sqrt d)."""
    out = {}
    for (a, b), r in rational_cos2_table(d).items():
        if 0 < r < Fraction(1, 2):
            c2 = Surd(a, b, d)
            out[((1-c2)/c2).key()] = r
    return out


def dihedral_data(vectors):
    """Per edge (i<j): (sign of cos theta_ij, cos^2 theta_ij) from Gram cofactors."""
    G = [[dot(u, v) for v in vectors] for u in vectors]
    out = {}
    for i, j in combinations(range(4), 2):
        k, m = [r for r in range(4) if r not in (i, j)]
        ckm, ckk, cmm = cofactor(G, k, m), cofactor(G, k, k), cofactor(G, m, m)
        out[(i, j)] = ((-ckm).sign(), ckm*ckm/(ckk*cmm))
    return G, out


def _all_irrational_tan2(name):
    """tan^2 (normalised to (0, pi/2)) of every irrational dihedral angle of the group."""
    d = FIELD[name]
    points = group_vectors(name)
    values = {}
    for t in classify_group(name)['types']:
        _, dihedral = dihedral_data([points[i] for i in t['representative_indices']])
        for sign, c2 in dihedral.values():
            if rational_angle(sign, c2) is None:
                T = (1-c2)/c2
                values[T.key()] = T
    return values


def _relations(name, values):
    """Exact identities among angles theta_T in (0, pi/2), tan^2 theta_T = T.

    Returns (description, {key: coefficient}, r) meaning sum c theta = r pi.
    complement : T_a T_b = 1                  => a + b = pi/2
    double     : tan^2 2a = 4T/(1-T)^2         => 2a = c (T<1) or pi - c (T>1)
    sum/diff   : s = sqrt(T_a T_b) in Q(sqrt d),
                 tan^2(a+b) = (Ta+Tb+2s)/(1-s)^2, a+b < pi/2 iff s < 1;
                 tan^2(a-b) = (Ta+Tb-2s)/(1+s)^2, sign by Ta - Tb.
    A target angle is either another theta_T or a rational multiple of pi.
    """
    d = FIELD[name]
    one = Surd(1, 0, d)
    rational = _tan2_rational_table(d)
    out = []

    def target(T):
        if T.key() in rational:
            return None, rational[T.key()]
        if T.key() in values:
            return T.key(), None
        return False, None

    def add(desc, lhs, T, reflect):
        key, r = target(T)
        if key is False:
            return
        rel = dict(lhs)
        if key is None:
            out.append((desc, rel, 1-r if reflect else r))
            return
        rel[key] = rel.get(key, 0)+(1 if reflect else -1)
        out.append((desc, {k: c for k, c in rel.items() if c}, Fraction(1) if reflect else Fraction(0)))

    keys = sorted(values)
    for a in keys:
        Ta = values[a]
        if Ta != one:
            add('double', {a: 2}, 4*Ta/((1-Ta)*(1-Ta)), Ta > one)
    for a, b in combinations(keys, 2):
        Ta, Tb = values[a], values[b]
        prod = Ta*Tb
        if prod == one:
            out.append(('complement', {a: 1, b: 1}, Fraction(1, 2)))
            continue
        root = surd_sqrt(prod)
        if root is None:
            continue
        add('sum', {a: 1, b: 1}, (Ta+Tb+2*root)/((1-root)*(1-root)), root > one)
        if Ta != Tb:
            big, small = (a, b) if Ta > Tb else (b, a)
            add('difference', {big: 1, small: -1}, (Ta+Tb-2*root)/((1+root)*(1+root)), False)
    return out


@lru_cache(maxsize=3)
def angle_system(name):
    """Certified expression of every irrational dihedral angle in the group basis.

    Returns {'basis': basis tan^2 keys, 'angles': {key: (r, {basis key: c})},
    'certificate': minimal list of exact identities used}. theta = r pi + sum c theta_basis.
    """
    _check_group(name)
    d = FIELD[name]
    values = _all_irrational_tan2(name)
    basis = tuple(Surd(T, 0, d).key() for T in BASIS_TAN2[name])
    if not set(basis) <= set(values):
        raise ArithmeticError('Basis angle does not occur as a dihedral angle')
    relations = _relations(name, values)
    keys = [k for k in sorted(values) if k not in basis]+list(basis)
    column = {k: i for i, k in enumerate(keys)}
    width = len(keys)+1
    pivots = {}
    used = []

    def reduce(row):
        for col, prow in pivots.items():
            if row[col]:
                f = row[col]
                row = [x-f*y for x, y in zip(row, prow)]
        return row

    def resolved():
        return all(column[k] in pivots and not any(pivots[column[k]][column[o]] for o in keys[:-len(basis) or None] if o != k)
                   for k in keys if k not in basis)
    for desc, rel, r in sorted(relations, key=lambda t: (len(t[1]), t[0])):
        row = [Fraction(0)]*width
        for k, c in rel.items():
            row[column[k]] += Fraction(c)
        row[-1] = Fraction(r)
        row = reduce(row)
        nz = [i for i in range(width-1) if row[i]]
        if not nz:
            if row[-1]:
                raise ArithmeticError('Contradictory angle identities')
            continue
        col = nz[0]
        if col >= len(keys)-len(basis):
            raise ArithmeticError('A relation among the chosen basis angles was found')
        row = [x/row[col] for x in row]
        for c2 in list(pivots):
            if pivots[c2][col]:
                f = pivots[c2][col]
                pivots[c2] = [x-f*y for x, y in zip(pivots[c2], row)]
        pivots[col] = row
        used.append((desc, rel, r))
        if resolved():
            break
    if not resolved():
        raise ArithmeticError('Angle identities do not reach the chosen basis')
    angles = {k: (Fraction(0), {k: Fraction(1)}) for k in basis}
    for k in keys:
        if k in basis:
            continue
        row = pivots[column[k]]
        angles[k] = (row[-1], {b: -row[column[b]] for b in basis if row[column[b]]})
    return {'basis': basis, 'angles': angles, 'certificate': tuple(used),
            'identity_count': len(relations)}


def basis_symbols(name):
    """SymPy constants arctan(sqrt(T)) for the basis angles of the group."""
    return tuple(s.atan(s.sqrt(s.Rational(T.numerator, T.denominator))) for T in BASIS_TAN2[name])


def dihedral_angle(name, sign, cos2):
    """theta = r pi + sum_j c_j Theta_j exactly; returns (r, coefficient tuple)."""
    r = rational_angle(sign, cos2)
    nb = len(BASIS_TAN2[name])
    if r is not None:
        return r, (Fraction(0),)*nb
    T = (1-cos2)/cos2
    system = angle_system(name)
    if T.key() not in system['angles']:
        raise ArithmeticError('Dihedral angle outside the certified table')
    r0, coeff = system['angles'][T.key()]
    c = tuple(coeff.get(b, Fraction(0)) for b in system['basis'])
    if sign < 0:                      # theta = pi - theta_T
        return 1-r0, tuple(-x for x in c)
    return r0, c


# ---------------------------------------------------------------------------
# Volumes, phases and the catalogue
# ---------------------------------------------------------------------------

def _as_indices(name, vertices):
    index = _index(name)
    points = group_vectors(name)
    out = []
    for v in vertices:
        if isinstance(v, int) and not isinstance(v, bool):
            if not 0 <= v < len(points):
                raise ValueError('Group index out of range')
            out.append(v)
            continue
        q = unit_quaternion(v)
        key = tuple(_surd_from_sympy(x, FIELD[name]).key() for x in q)
        if key not in index:
            raise ValueError('An input is not a member of '+name)
        out.append(index[key])
    return tuple(out)


def _surd_from_sympy(x, d):
    """Exact coordinates in Q(sqrt d) by algebraic rewriting only (no nsimplify)."""
    x = s.expand(s.radsimp(s.expand(s.sympify(x))))
    if d:
        b = x.coeff(s.sqrt(d))
        a = s.expand(x-b*s.sqrt(d))
    else:
        a, b = x, s.Integer(0)
    if not (a.is_Rational and b.is_Rational):
        raise ValueError('Coordinate outside Q(sqrt d)')
    return Surd(Fraction(int(a.p), int(a.q)), Fraction(int(b.p), int(b.q)), d)


def tetrahedron_volume(name, vertices, k=1):
    """Exact Li2-free volume of the tetrahedron spanned by four group elements.

    V = a pi^2 + (pi/2) sum_j b_j Theta_j with rational a, b_j (actual volume in
    (0, pi^2), not only modulo 2 pi^2). Orientation is sgn det(vertices).
    """
    _check_group(name)
    k = exact_level(k)
    idx = _as_indices(name, vertices)
    points = group_vectors(name)
    P = [points[i] for i in idx]
    det = determinant(P)
    if det.sign() == 0:
        raise ValueError('Degenerate tetrahedron: use the global chain')
    G, dihedral = dihedral_data(P)
    order, N = chamber_count(name, idx)
    nb = len(BASIS_TAN2[name])
    edges = []
    a = 1-Fraction(2*N, order)
    b = [Fraction(0)]*nb
    for i, j in EDGE_PAIRS:            # user order (01,02,03,23,13,12)
        q = edge_fraction(G[i][j])
        sign, c2 = dihedral[(min(i, j), max(i, j))]
        r, c = dihedral_angle(name, sign, c2)
        a += (q*r-q)/2
        for t in range(nb):
            b[t] += q*c[t]
        edges.append({'edge': (i, j), 'length_over_pi': q, 'dihedral_sign': sign,
                      'dihedral_cos2': c2.sympy(), 'dihedral': (r, c)})
    theta = basis_symbols(name)
    volume = s.Rational(a.numerator, a.denominator)*s.pi**2 \
        + s.pi/2*sum((s.Rational(x.numerator, x.denominator)*t for x, t in zip(b, theta)), s.S.Zero)
    orientation = det.sign()
    exponent = s.Rational(a.numerator, a.denominator)*s.pi \
        + sum((s.Rational(x.numerator, x.denominator)*t for x, t in zip(b, theta)), s.S.Zero)/2
    return {'group': name, 'indices': idx, 'orientation': orientation,
            'chambers': N, 'weyl_order': order, 'edges': tuple(edges),
            'rational_part': a, 'basis_coefficients': tuple(b),
            'basis': theta, 'volume': volume, 'oriented_volume': orientation*volume,
            'rational_volume': not any(b),
            'phase': s.exp(-s.I*k*orientation*exponent),
            'method': 'polar dual + Schlaefli + Coxeter chambers (same tetrahedron)'}


def polar_formula(name, g1, g2, g3, k=1):
    """Three group elements -> cumulative vertices (1, g1, g1g2, g1g2g3) -> exact phase."""
    _check_group(name)
    points = group_vectors(name)
    index = _index(name)
    i1, i2, i3 = _as_indices(name, (g1, g2, g3))
    one = index[tuple(Surd(x, 0, FIELD[name]).key() for x in (1, 0, 0, 0))]
    p2 = quaternion_product(points[i1], points[i2])
    p3 = quaternion_product(p2, points[i3])
    j2, j3 = index[tuple(x.key() for x in p2)], index[tuple(x.key() for x in p3)]
    return tetrahedron_volume(name, (one, i1, j2, j3), k=k)


@lru_cache(maxsize=3)
def _catalogue(name):
    rows = []
    for t in classify_group(name)['types']:
        r = tetrahedron_volume(name, t['representative_indices'])
        rows.append({'gram_key': t['gram_key'], 'anchored_multiplicity': t['anchored_multiplicity'],
                     'representative_indices': t['representative_indices'],
                     'chambers': r['chambers'], 'rational_part': r['rational_part'],
                     'basis_coefficients': r['basis_coefficients'],
                     'rational_volume': r['rational_volume'], 'volume': r['volume']})
    order, _ = weyl_chamber_masks(name)
    return {'group': name, 'weyl_order': order, 'basis_tan2': BASIS_TAN2[name],
            'basis': basis_symbols(name), 'types': tuple(rows)}


def polar_catalogue(name):
    """Every nondegenerate unoriented type with its exact Li2-free volume."""
    return deepcopy(_catalogue(name))
